// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9b7j7A8Jq8jURBkUOuI5MH7wVGZr3GNY',
    appId: '1:326477674546:web:a856f71c6b734cc7d5242b',
    messagingSenderId: '326477674546',
    projectId: 'fomo23-4c71d',
    authDomain: 'fomo23-4c71d.firebaseapp.com',
    storageBucket: 'fomo23-4c71d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJytdC200lhwq0_X67nDJbNhIzAjh-NM',
    appId: '1:326477674546:android:c4b18163e8b072cfd5242b',
    messagingSenderId: '326477674546',
    projectId: 'fomo23-4c71d',
    storageBucket: 'fomo23-4c71d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvOI21EO-1GWTme57OuQYBix0wA75gRg',
    appId: '1:326477674546:ios:28549fc47a1a099cd5242b',
    messagingSenderId: '326477674546',
    projectId: 'fomo23-4c71d',
    storageBucket: 'fomo23-4c71d.firebasestorage.app',
    iosBundleId: 'com.example.fomo23App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTvOI21EO-1GWTme57OuQYBix0wA75gRg',
    appId: '1:326477674546:ios:28549fc47a1a099cd5242b',
    messagingSenderId: '326477674546',
    projectId: 'fomo23-4c71d',
    storageBucket: 'fomo23-4c71d.firebasestorage.app',
    iosBundleId: 'com.example.fomo23App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9b7j7A8Jq8jURBkUOuI5MH7wVGZr3GNY',
    appId: '1:326477674546:web:6225c7a8b29cbb2ad5242b',
    messagingSenderId: '326477674546',
    projectId: 'fomo23-4c71d',
    authDomain: 'fomo23-4c71d.firebaseapp.com',
    storageBucket: 'fomo23-4c71d.firebasestorage.app',
  );
}
